name: iconvert
description: "iConvert - 全格式转换器侧载版"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ffmpeg_kit_flutter_new: ^4.3.2
  provider: ^6.1.1
  file_picker: ^11.0.0
  permission_handler: ^11.3.0
  flutter_foreground_task: ^6.1.0
  shared_preferences: ^2.2.2
  path: ^1.9.0
  open_filex: ^4.5.0
  url_launcher: ^6.2.5
  quick_actions: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
